<?php
/**
 * @file
 * student_type.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function student_type_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'student-student-field_transfer_type'
  $field_instances['student-student-field_transfer_type'] = array(
    'bundle' => 'student',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'If this student was transferred, please indicate which type of transfer was completed.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'student',
    'exclude_cv' => 0,
    'field_name' => 'field_transfer_type',
    'label' => 'Transfer Type',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'student-student-og_group_ref'
  $field_instances['student-student-og_group_ref'] = array(
    'bundle' => 'student',
    'default_value' => NULL,
    'default_value_function' => 'entityreference_prepopulate_field_default_value',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'og_ui',
        'settings' => array(),
        'type' => 'og_list_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'student',
    'field_name' => 'og_group_ref',
    'label' => 'School',
    'required' => 1,
    'settings' => array(
      'behaviors' => array(
        'og_widget' => array(
          'admin' => array(
            'widget_type' => 'entityreference_autocomplete',
          ),
          'default' => array(
            'widget_type' => 'entityreference_autocomplete',
          ),
          'status' => TRUE,
        ),
        'prepopulate' => array(
          'action' => 'none',
          'action_on_edit' => 0,
          'fallback' => 'none',
          'og_context' => 1,
          'skip_perm' => 'bypass node access',
          'status' => 1,
        ),
      ),
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'view modes' => array(
      'full' => array(
        'custom settings' => FALSE,
        'label' => 'Full',
        'type' => 'og_list_default',
      ),
      'teaser' => array(
        'custom settings' => FALSE,
        'label' => 'Teaser',
        'type' => 'og_list_default',
      ),
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'entityreference',
      'settings' => array(
        'match_operator' => 'CONTAINS',
        'path' => '',
        'size' => 60,
      ),
      'type' => 'entityreference_autocomplete',
      'weight' => 3,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('If this student was transferred, please indicate which type of transfer was completed.');
  t('School');
  t('Transfer Type');

  return $field_instances;
}
